### ISSUE TITLE
the test does not pass

### ISSUE THREAD

**Issue by marcusthierfelder** [getsenic/nuimo-swift-demo-osx#1]
the test testNuimoControllerDisplaysLEDMatrixAnimation is failing. I think in line 89 (NumioTest.swift) 
case 110: 
is wrong

**Comment by larsblumberg** [comment]
Thank you for your message! I will have a look into the test cases. Tests are however not implemented in this project but here: https://github.com/getsenic/nuimo-swift

**Comment by larsblumberg** [comment]
Test fixed in getsenic/nuimo-swift@6ad51f3
